

OHLCV_TIMEFRAMES             = ['1s', '5s', '10s', '15s', '20s', '30s', '1m', '5m', '10m', '15m', '20m', '30m', '1h', '2h', '3h', '4h', '6h', '8h', '12h', '1d', '1w']

BASE_DIRECTORY__DATA         = 'DATA'
DIRECTORY_NAME__TICK_CSV     = '1-RAW_TICK_STR_CSV'
DIRECTORY_NAME__TICK_PARQUET = '1-RAW_TICK_STR_PARQUET'
DIRECTORY_NAME__PREP_CSV     = '2-PREPROCESSED_CSV'
DIRECTORY_NAME__PREP_PARQUET = '2-PREPROCESSED_PARQUET'
DIRECTORY_NAME__AGGR_CSV     = '3-OHLCV_CSV'
DIRECTORY_NAME__AGGR_PARQUET = '3-OHLCV_PARQUET'
DIRECTORY_NAME__AGGR_DB      = '3-OHLCV_STR_DATABASE'

VOLUME_PRECISION             = '0.0001'
TIMESTAMP_PRECISION          = '0.000001'
PRICE_PRECISION              = '0.00000001'
