

BASE_DIRECTORY__DATA         = 'DATA'
DIRECTORY_NAME__TICK_CSV     = '1-TICK_CSV'
DIRECTORY_NAME__TICK_PARQUET = '1-TICK_PARQUET'
DIRECTORY_NAME__PREP_CSV     = '2-PREPROCESSED_CSV'
DIRECTORY_NAME__PREP_PARQUET = '2-PREPROCESSED_PARQUET'

TIMESTAMP_PRECISION          = '0.000001'
PRICE_PRECISION              = '0.00000001'
